# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(749, 525)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.nLineEdit = QtWidgets.QLineEdit(Form)
        self.nLineEdit.setObjectName("nLineEdit")
        self.horizontalLayout.addWidget(self.nLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.sLineEdit = QtWidgets.QLineEdit(Form)
        self.sLineEdit.setObjectName("sLineEdit")
        self.horizontalLayout_2.addWidget(self.sLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.tLineEdit = QtWidgets.QLineEdit(Form)
        self.tLineEdit.setObjectName("tLineEdit")
        self.horizontalLayout_3.addWidget(self.tLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.epochsLineEdit = QtWidgets.QLineEdit(Form)
        self.epochsLineEdit.setObjectName("epochsLineEdit")
        self.horizontalLayout_4.addWidget(self.epochsLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.populationLineEdit = QtWidgets.QLineEdit(Form)
        self.populationLineEdit.setObjectName("populationLineEdit")
        self.horizontalLayout_6.addWidget(self.populationLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.alpha = QtWidgets.QLabel(Form)
        self.alpha.setObjectName("alpha")
        self.horizontalLayout_7.addWidget(self.alpha)
        self.alphaLineEdit = QtWidgets.QLineEdit(Form)
        self.alphaLineEdit.setObjectName("alphaLineEdit")
        self.horizontalLayout_7.addWidget(self.alphaLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.betaLineEdit = QtWidgets.QLineEdit(Form)
        self.betaLineEdit.setObjectName("betaLineEdit")
        self.horizontalLayout_9.addWidget(self.betaLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.rhoLineEdit = QtWidgets.QLineEdit(Form)
        self.rhoLineEdit.setObjectName("rhoLineEdit")
        self.horizontalLayout_10.addWidget(self.rhoLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_11.addWidget(self.label_10)
        self.probabilityLineEdit = QtWidgets.QLineEdit(Form)
        self.probabilityLineEdit.setObjectName("probabilityLineEdit")
        self.horizontalLayout_11.addWidget(self.probabilityLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.goButton = QtWidgets.QPushButton(Form)
        self.goButton.setObjectName("goButton")
        self.horizontalLayout_8.addWidget(self.goButton)
        self.stopButton = QtWidgets.QPushButton(Form)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_8.addWidget(self.stopButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.currentEpochLineEdit = QtWidgets.QLineEdit(Form)
        self.currentEpochLineEdit.setObjectName("currentEpochLineEdit")
        self.verticalLayout_3.addWidget(self.currentEpochLineEdit)
        self.currentIterationButton = QtWidgets.QPushButton(Form)
        self.currentIterationButton.setObjectName("currentIterationButton")
        self.verticalLayout_3.addWidget(self.currentIterationButton)
        self.validateButton = QtWidgets.QPushButton(Form)
        self.validateButton.setObjectName("validateButton")
        self.verticalLayout_3.addWidget(self.validateButton)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.solutionTextEdit = QtWidgets.QTextEdit(Form)
        self.solutionTextEdit.setObjectName("solutionTextEdit")
        self.verticalLayout_4.addWidget(self.solutionTextEdit)
        self.bestSolutionButton = QtWidgets.QPushButton(Form)
        self.bestSolutionButton.setObjectName("bestSolutionButton")
        self.verticalLayout_4.addWidget(self.bestSolutionButton)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "n ="))
        self.label_2.setText(_translate("Form", "s ="))
        self.label_3.setText(_translate("Form", "t ="))
        self.label_4.setText(_translate("Form", "epochs="))
        self.label_7.setText(_translate("Form", "population="))
        self.alpha.setText(_translate("Form", "alpha="))
        self.label_8.setText(_translate("Form", "beta="))
        self.label_9.setText(_translate("Form", "evaporation="))
        self.label_10.setText(_translate("Form", "choiceProbability="))
        self.goButton.setText(_translate("Form", "GO"))
        self.stopButton.setText(_translate("Form", "STOP"))
        self.currentIterationButton.setText(_translate("Form", "Get current iteration"))
        self.validateButton.setText(_translate("Form", "Validate"))
        self.bestSolutionButton.setText(_translate("Form", "Get best solution"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
