# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(749, 525)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.nLineEdit = QtWidgets.QLineEdit(Form)
        self.nLineEdit.setObjectName("nLineEdit")
        self.horizontalLayout.addWidget(self.nLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.sLineEdit = QtWidgets.QLineEdit(Form)
        self.sLineEdit.setObjectName("sLineEdit")
        self.horizontalLayout_2.addWidget(self.sLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.tLineEdit = QtWidgets.QLineEdit(Form)
        self.tLineEdit.setObjectName("tLineEdit")
        self.horizontalLayout_3.addWidget(self.tLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.iterationsLineEdit = QtWidgets.QLineEdit(Form)
        self.iterationsLineEdit.setObjectName("iterationsLineEdit")
        self.horizontalLayout_4.addWidget(self.iterationsLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.mutationLineEdit = QtWidgets.QLineEdit(Form)
        self.mutationLineEdit.setObjectName("mutationLineEdit")
        self.horizontalLayout_5.addWidget(self.mutationLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.populationLineEdit = QtWidgets.QLineEdit(Form)
        self.populationLineEdit.setObjectName("populationLineEdit")
        self.horizontalLayout_6.addWidget(self.populationLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.inertiaLineEdit = QtWidgets.QLineEdit(Form)
        self.inertiaLineEdit.setObjectName("inertiaLineEdit")
        self.horizontalLayout_7.addWidget(self.inertiaLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.cognitiveLineEdit = QtWidgets.QLineEdit(Form)
        self.cognitiveLineEdit.setObjectName("cognitiveLineEdit")
        self.horizontalLayout_9.addWidget(self.cognitiveLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.socialLineEdit = QtWidgets.QLineEdit(Form)
        self.socialLineEdit.setObjectName("socialLineEdit")
        self.horizontalLayout_10.addWidget(self.socialLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_11.addWidget(self.label_10)
        self.neighbourhoodLineExit = QtWidgets.QLineEdit(Form)
        self.neighbourhoodLineExit.setObjectName("neighbourhoodLineExit")
        self.horizontalLayout_11.addWidget(self.neighbourhoodLineExit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.hcRadioButton = QtWidgets.QRadioButton(Form)
        self.hcRadioButton.setObjectName("hcRadioButton")
        self.verticalLayout.addWidget(self.hcRadioButton)
        self.eaRadioButton = QtWidgets.QRadioButton(Form)
        self.eaRadioButton.setObjectName("eaRadioButton")
        self.verticalLayout.addWidget(self.eaRadioButton)
        self.psoRadioButton = QtWidgets.QRadioButton(Form)
        self.psoRadioButton.setObjectName("psoRadioButton")
        self.verticalLayout.addWidget(self.psoRadioButton)
        self.horizontalLayout_12.addLayout(self.verticalLayout)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.goButton = QtWidgets.QPushButton(Form)
        self.goButton.setObjectName("goButton")
        self.horizontalLayout_8.addWidget(self.goButton)
        self.stopButton = QtWidgets.QPushButton(Form)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_8.addWidget(self.stopButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_3.addWidget(self.lineEdit)
        self.currentIterationButton = QtWidgets.QPushButton(Form)
        self.currentIterationButton.setObjectName("currentIterationButton")
        self.verticalLayout_3.addWidget(self.currentIterationButton)
        self.validateEAButton = QtWidgets.QPushButton(Form)
        self.validateEAButton.setObjectName("validateEAButton")
        self.verticalLayout_3.addWidget(self.validateEAButton)
        self.validatePSOButton = QtWidgets.QPushButton(Form)
        self.validatePSOButton.setObjectName("validatePSOButton")
        self.verticalLayout_3.addWidget(self.validatePSOButton)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.horizontalLayout_13.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.solutionTextEdit = QtWidgets.QTextEdit(Form)
        self.solutionTextEdit.setObjectName("solutionTextEdit")
        self.verticalLayout_4.addWidget(self.solutionTextEdit)
        self.bestSolutionButton = QtWidgets.QPushButton(Form)
        self.bestSolutionButton.setObjectName("bestSolutionButton")
        self.verticalLayout_4.addWidget(self.bestSolutionButton)
        self.horizontalLayout_13.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "n ="))
        self.label_2.setText(_translate("Form", "s ="))
        self.label_3.setText(_translate("Form", "t ="))
        self.label_4.setText(_translate("Form", "iterations="))
        self.label_5.setText(_translate("Form", "mutation="))
        self.label_7.setText(_translate("Form", "population="))
        self.label_6.setText(_translate("Form", "inertia="))
        self.label_8.setText(_translate("Form", "cognitive="))
        self.label_9.setText(_translate("Form", "social="))
        self.label_10.setText(_translate("Form", "nbhdsize ="))
        self.hcRadioButton.setText(_translate("Form", "HC"))
        self.eaRadioButton.setText(_translate("Form", "EA"))
        self.psoRadioButton.setText(_translate("Form", "PSO"))
        self.goButton.setText(_translate("Form", "GO"))
        self.stopButton.setText(_translate("Form", "STOP"))
        self.currentIterationButton.setText(_translate("Form", "Get current iteration"))
        self.validateEAButton.setText(_translate("Form", "Validate EA Plot"))
        self.validatePSOButton.setText(_translate("Form", "Validate PSO Plot"))
        self.bestSolutionButton.setText(_translate("Form", "Get best solution"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

